### ISSUE TITLE
Link updates for Java versions of SmallWorld

### ISSUE THREAD

**Issue by davidedc** [crcx/littlesmalltalk#1]
The smallworld directory contains a version that is not working anymore ( due to ArrayIndexOutOfBound because of implementation assumption of Object.hashCode() which has changed over time) - The author Russell Allen has recently updated his 2007's version here: https://github.com/russellallen/SmallWorld

So probably worth replacing the contents of the smallworld directory with an .md linking to that repo?

Also there is another link worth adding: to a working version of SmallWorld here: https://github.com/ericscharff/SmallWorld where the author Eric Scharff has made independent refactoring - also it contains some of the original classes referenced in Russels' online tutorials (i.e. Image, Color) here: http://web.engr.oregonstate.edu/~budd/SmallWorld/Book/index.html . Curiously, Russel has temporarily removed those classes in the 2007 version and 2015 version, but they are in this one from Eric, which is cool because one can play with Turtle Graphics...

They both run fine on current OSX / Java 8 setup (Eric's requires gradle to build).

**Comment by crcx** [comment]
I have updated the repository and included links to these. Thanks!
